ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    # Frames
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Inputs
    odom0: /t265/odom
    odom0_config: [true, true, true,
                   true, true, true,
                   true, true, true,
                   true, true, true,
                   false, false, false]
    odom0_differential: false

    odom1: /diffbot_base_controller/odom
    odom1_config: [true, true, false,
                   false, false, true,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom1_differential: false