ekf_global:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.2
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    publish_tf: true
    publish_acceleration: false
    transform_time_offset: 0.05 # Fix rviz bug

    # Fuse GPS (from navsat_transform) as position in map frame
    odom0: /odometry/gps
    odom0_config: [true,  true,  false,
                   false, false, false,
                  false, false, false,
                 false, false, false,
                  false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_pose_rejection_threshold: 5.0
    odom0_twist_rejection_threshold: 1.0
    odom0_qos_overrides:
      reliability: reliable

    # Fuse local filtered odom (position + yaw + velocities)
    odom1: /odometry/filtered/local
    odom1_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom1_differential: false
    odom1_relative: false

    # Earth-referenced IMU heading
    imu0: imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                 false, false, false,
                  false,  false,  false,
                  false, false, false]
    imu0_differential: false

