ekf_local:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    # Frames
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf : true

    # Inputs
    odom0: /t265/odom
    odom0_config: [true, true, true,
                   true, true, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    odom1: /diffbot_base_controller/odom
    odom1_config: [false, false, false,
                   false, false, false,
                   true, false, false,
                   false, false, true,
                   false, false, false]
    odom1_differential: false

    #imu0: /bno055/imu
    #imu0_config: [false, false, false,
    #          false,  false,  true,
    #          false, false, false,
    #          false,  false,  false,
    #          false,  false,  false]
    #imu0_differential: false