ekf_local:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true  
    transform_time_offset: 0.05 # Fix rviz bug

    # Frames
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf : true

    # Inputs
    odom0: /diffbot_base_controller/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  false, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false


    # Earth-referenced IMU heading
    imu0: imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false,  false,  true,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false