navsat_transform_node:
  ros__parameters:
    frequency: 10.0
    delay: 0.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: false
    use_odometry_yaw: false

    # Frames (match your robot)
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
