navsat_transform:
  ros__parameters:
    frequency: 10.0
    delay: 0.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    use_odometry_yaw: false

    # future config
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0

    # Frames (match your robot)
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link

    # Topics
    gps_topic: /gps/fix # input
    odometry_topic: /odometry/gps # output
    imu_topic: /bno055/imu 
