image: /home/youssef/imprimis/imprimis_ws/src/imprimis_navigation/config/nav2_blank_map/bigger_blank.pgm
mode: trinary
resolution: 0.5
origin: [-100.0, -100.0, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25